
Vagrant.configure(2) do |config|
    config.vm.define "dockerhost" do |dockerhost|
        dockerhost.vm.box = "williamyeh/ubuntu-trusty64-docker"
		dockerhost.vm.hostname = "dockerhost"
        dockerhost.vm.network "private_network", ip: "192.168.33.30"
        dockerhost.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=775,fmode=444"]
	end
end
