version: '2'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  prometheus:
    image: 'prom/prometheus'
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command: [
        '-alertmanager.url=http://alertmanager:9093',
        '-config.file=/etc/prometheus/prometheus.yml',
        '-storage.local.path=/prometheus',
        '-web.console.libraries=/etc/prometheus/console_libraries',
        '-web.console.templates=/etc/prometheus/consoles'
    ]
    depends_on:
      - alertmanager
    mem_limit: 1g
    restart: always

  alertmanager:
    image: prom/alertmanager
    ports:
      - '9093:9093'
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command: [
        '-config.file=/etc/alertmanager/config.yml',
        '-storage.path=/alertmanager'
    ]
    restart: always

  grafana:
    image: 'grafana/grafana'
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: secret
      GF_INSTALL_PLUGINS: 'mtanda-histogram-panel,grafana-piechart-panel,savantly-heatmap-panel,jdbranham-diagram-panel,vonage-status-panel,grafana-worldmap-panel,briangann-gauge-panel'
    restart: always
