global:
  # How frequently to scrape targets by default.
  scrape_interval:     15s

  # How frequently to evaluate rules.
  evaluation_interval: 15s

  # How long until a scrape request times out.
  scrape_timeout: 15s

rule_files:
  - 'prometheus.rules'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'PlanetExpressDelivery'
    static_configs:
      - targets: ['10.0.75.1:1234']
